config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :twitts, only: [:create] do
    post "like", to: "twitts#like", on: :member
  end

  root "twitts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twitt.rb
class Twitt < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 140 }

  after_create_commit :broadcast_create
  after_update_commit :broadcast_update

  private

  def broadcast_create
    Turbo::StreamsChannel.broadcast_prepend_to("twitts",
      target: "twitts",
      partial: "twitts/twitt",
      locals: { twitt: self })
  end

  def broadcast_update
    Turbo::StreamsChannel.broadcast_replace_to("twitts",
    target: self,
    partial: "twitts/twitt",
    locals: { twitt: self })
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
end

app/controllers/twitts_controller.rb
class TwittsController < ApplicationController
  def index
    @twitts = Twitt.order(created_at: :desc)
    @twitt = Twitt.new
  end

  def create
    @twitt = current_user.twitts.new(twitt_params)
    @twitt = Twitt.new if @twitt.save

    render turbo_stream: turbo_stream.replace('twitts_form',
      partial: 'twitts/form',
      locals: { twitt: @twitt })
  end

  def like
    twitt = Twitt.find(params[:id])
    twitt.like += 1
    twitt.save!
  end

  private

  def twitt_params
    params.require(:twitt).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitts_helper.rb
module TwittsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Twitts!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "SignUp", new_user_registration_path, class: 'nav-link active' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Twitter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/twitts/_form.html.erb
<%= turbo_frame_tag "twitts_form" do %>
  <%= simple_form_for twitt do |f| %>
    <%= f.input :content, label: "What's happening" %>
    <%= f.submit "Post", class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/twitts/_twitt.html.erb
<%= turbo_frame_tag twitt do %>
  <div class="card mt-3">
    <div class="card-header">
      <%= twitt.user.email %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= twitt.content %></h5>
      <p class="card-text">Created at <%= time_ago_in_words(twitt.created_at) %> ago</p>
      <p>
        <%= simple_form_for twitt, url: like_twitt_path(twitt), method: :posto do |f| %>
          <%= f.submit "Like", class: 'btn btn-danger' %>
        <% end %>
        Likes: <%= twitt.like %>
      </p>
    </div>
  </div>
<% end %>

app/views/twitts/index.html.erb
<%= turbo_stream_from "twitts" %>
<div class="container">
  <%= render 'form', twitt: @twitt %>
  <%= turbo_frame_tag "twitts" do %>
    <%= render @twitts %>
  <% end %>
</div>